---
- name: Set facts for interface '{{ ifname }}'
  ansible.builtin.set_fact:
    if_config: "{{ wg_config[ifname] }}"

- name: Enable interface '{{ ifname }}'
  ansible.builtin.command: nmcli connection modify '{{ ifname }}' connection.autoconnect yes
  when: ("enable" in if_config) and (if_config["enable"] | bool)

- name: Disable interface '{{ ifname }}'
  ansible.builtin.command: nmcli connection modify '{{ ifname }}' connection.autoconnect no
  when: ("enable" in if_config) and not (if_config["enable"] | bool)

# - name: Enable interface '{{ ifname }}'
#   ansible.builtin.nmcli:
#     conn_name: "{{ ifname }}"
#     autoconnect: "{{ if_config['enable'] }}"
#   when: ("enable" in if_config)
