---
- name: Set facts for interface '{{ ifname }}'
  ansible.builtin.set_fact:
    if_config: "{{ wg_config[ifname] }}"

- name: Start interface '{{ ifname }}'
  ansible.builtin.command: nmcli c up '{{ ifname }}'
  when: ("start" in if_config) and (if_config["start"] | bool)

- name: Stop interface '{{ ifname }}'
  ansible.builtin.command: nmcli c up '{{ ifname }}'
  when: ("start" in if_config) and (if_config["start"] | bool)