---
- name: Set interface '{{ ifname }}' facts
  ansible.builtin.set_fact:
    if_config: "{{ wg_config[ifname] }}"

- name: Start interface '{{ ifname }}' if necessary
  ansible.builtin.command: nmcli c up '{{ ifname }}'
  when: ("start" in if_config) and (if_config["start"] == true)

- name: Stop interface '{{ ifname }}' if necessary
  ansible.builtin.command: nmcli c up '{{ ifname }}'
  when: ("start" in if_config) and (if_config["start"] == false)