---
- name: Set interface '{{ ifname }}' facts
  ansible.builtin.set_fact:
    service_name: "wg-quick@{{ ifname }}.service"
    if_config: "{{ wg_config[ifname] }}"

- name: Enable interface '{{ ifname }}' with wg-quick if necessary
  ansible.builtin.systemd:
    name: wg-quick@{{ ifname }}.service
    enabled: yes
  when: ("enable" in if_config) and (if_config["enable"] == true)

- name: Reload interface '{{ ifname }}' configuration with wg-quick if necessary
  ansible.builtin.systemd:
    name: "{{ service_name }}"
    state: reloaded
  when: ("start" in if_config) and (if_config["start"] == true) and
    ( (service_name in services_facts) and (services_facts[service_name].state == "running") )

- name: Start interface '{{ ifname }}' with wg-quick if necessary
  ansible.builtin.systemd:
    name: "{{ service_name }}"
    state: started
  when: ("start" in if_config) and (if_config["start"] == true) and
    ( (service_name not in services_facts) or (services_facts[service_name].state != "running") )