---
- name: Check if private key already exists
  ansible.builtin.set_fact:
    __wg_gen_keys: true
    __wg_if_config: "{{ wg_config[item] }}"
  when:
    - '"private_key" not in wg_config[item]'
  
- name: Generate private key
  ansible.builtin.command: "wg genkey"
  register: __wg_tmp_private_key
  changed_when: false
  tags:
    - wireguard_generate_keys
    - wireguard_configure
  when:
    - __wg_gen_keys is defined

- name: Register new private key
  ansible.builtin.set_fact:
    __wg_if_config: "{{ __wg_if_config | combine({'private_key': __wg_tmp_private_key.stdout}) }}"
  tags:
    - wireguard_generate_keys
    - wireguard_configure
  when:
    - __wg_gen_keys is defined

- name: Derive public key
  ansible.builtin.command: "wg pubkey"
  args:
    stdin: "{{ __wg_if_config['private_key'] }}"
  register: __wg_tmp_public_key
  changed_when: false
  check_mode: false
  tags:
    - wireguard_generate_keys
    - wireguard_configure
  when:
    - __wg_gen_keys is defined

- name: Register public key
  ansible.builtin.set_fact:
    __wg_if_config: "{{ __wg_if_config | combine({'public_key': __wg_tmp_public_key.stdout}) }}"
  tags:
    - wireguard_generate_keys
    - wireguard_configure
  when:
    - __wg_gen_keys is defined

- name: Save new configuration
  ansible.builtin.set_fact:
    wg_config: "{{ wg_config | combine({ item: __wg_if_config })}}"
  tags:
    - wireguard_generate_keys
    - wireguard_configure
  when:
    - __wg_gen_keys is defined